build-ubuntu:
  image: ubuntu:rolling
  before_script:
    - apt-get update
    - apt-get install -q -y --no-install-recommends gobject-introspection gtk-doc-tools gettext-dev libglib2.0-dev libpolkit-gobject-1-dev libsystemd-dev libtool
  script:
    - ./autogen.sh --enable-gtk-doc --with-systemdsystemunitdir=/lib/systemd/system
    - make distcheck

build-fedora:
  image: fedora:latest
  before_script:
    - dnf install -y gcc gettext-devel gobject-introspection-devel glib-devel gtk-doc make pkgconf-m4 polkit-devel redhat-rpm-config systemd-devel
  script:
    - ./autogen.sh --enable-gtk-doc
    - make distcheck
