variables:
  DEPENDENCIES: dbus-devel
                gcc
                gettext-devel
                glib-devel
                gobject-introspection-devel
                gtk-doc
                make
                meson
                ninja-build
                polkit-devel
                redhat-rpm-config
                systemd-devel
                vala

build-fedora:
  image: fedora:rawhide
  stage: build
  before_script:
    - dnf install -y $DEPENDENCIES
  script:
    - meson -Dgtk_doc=true _build
    - ninja -C _build all

#build-ubuntu:
#  image: ubuntu:rolling
#  before_script:
#    - apt-get update
#    - apt-get install -q -y --no-install-recommends meson ninja-build gobject-introspection gtk-doc-tools gettext libglib2.0-dev libpolkit-gobject-1-dev libsystemd-dev libdbus-1-dev
#  script:
#    - meson -Dgtk_doc=true _build
#    - ninja -C _build all

